- name: Ping
  hosts: online:&tag_workstations
  tags: [ping]
  become: true
  gather_facts: true
  roles:
    - ping

- name: Init
  hosts: online:&tag_workstations
  tags: [init]
  become: true
  gather_facts: false
  roles:
    - init

- name: Home Assistant
  hosts: online:&tag_homeassistant
  tags: [homeassistant]
  become: true
  gather_facts: true
  roles:
    - homeassistant
