- name: Linux Online VMs
  hosts: linux:&online
  become: true
  gather_facts: true
  roles:
    - {role: linux_ping, tags: [always, ping]}

- name: Linux Online non-self VMs
  hosts: linux:&online:!self # linux:&online:&tag_vagrantvms
  become: true
  gather_facts: false
  roles:
    - {role: linux_init, tags: [init]}
    - {role: linux_storage, tags: [storage]}

- name: Linux Home Assistant VMs
  hosts: linux:&online:&tag_homeassistant
  become: true
  gather_facts: false
  roles:
    - {role: linux_homeassistant, tags: [homeassistant]}

# - name: Linux Landscape Server
#   hosts: vagrantvm-1 # linux:&online:&tag_landscape_server
#   become: true
#   gather_facts: false
#   roles:
#     - {role: linux_landscape_server, tags: [landscape_server, landscape]}

# - name: Linux Landscape Clients
#   hosts: vagrantvm-2 # linux:&online:&tag_landscape_client
#   become: true
#   gather_facts: false
#   roles:
#     - {role: linux_landscape_client, tags: [landscape_client, landscape]}
