- name: Start home assistant
  containers.podman.podman_container:
    name: homeassistant
    privileged: true
    restart_policy: "on-failure"
    env:
      TZ: "America/Chicago"
    volumes:
      - "/opt/homeassistant:/config"
      - "/run/dbus:/run/dbus:ro"
    network: host
    image: "ghcr.io/home-assistant/home-assistant:stable"
    state: started

- name: Open firewall for 8123/tcp
  ansible.posix.firewalld:
    port: 8123/tcp
    permanent: true
    immediate: true
    state: enabled

- name: URL for Home Assistant
  ansible.builtin.debug:
    msg: "http://{{ ansible_host }}:8123"
