name: Calculate ansible inventory from python script

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ansible-inventory:
    name: Calculate ansible inventory
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      TAILNET_ID: ${{ secrets.TAILNET_ID }}
      TAILNET_APIKEY: ${{ secrets.TAILNET_APIKEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        if: env.TAILNET_ID != ''

      - name: Set up Python
        uses: actions/setup-python@v5
        if: env.TAILNET_ID != ''
        with:
          python-version: '3.12'

      - name: Run python script, but don't display output
        id: run_inventory
        if: env.TAILNET_ID != ''
        run: |
          # Run the script and write output to a temporary file (discards stdout print)
          python3 ansible_tailscale_inventory_api.py > inventory_output.json
          
          # # Set the file content as a multiline output variable
          # echo "inventory<<EOF" >> "$GITHUB_OUTPUT"
          # cat inventory_output.json >> "$GITHUB_OUTPUT"
          # echo "EOF" >> "$GITHUB_OUTPUT"

      - name: Verify inventory output contains values
        if: env.TAILNET_ID != ''
        run: |
          INVENTORY_JSON=$(cat inventory_output.json)
          # Verify that the registered output variable is not empty
          if [ -z "$INVENTORY_JSON" ]; then
            echo "Error: Inventory output is empty."
            exit 1
          fi
          
          # Verify it is valid JSON and contains hosts in the 'all' group
          # (Redirect stdout to /dev/null to ensure secret details are not printed in the logs)
          echo "$INVENTORY_JSON" | jq -e '.all.hosts | length > 0' > /dev/null
          if [ $? -ne 0 ]; then
            echo "Error: Verification failed. Inventory does not contain any hosts in the 'all' group."
            exit 1
          fi
          
          echo "Success: Inventory verified successfully and contains hosts."
